name: Deploy to Streamlit Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy to Streamlit Cloud
        uses: streamlit/actions/deploy@main
        with:
          streamlit_token: ${{ secrets.STREAMLIT_TOKEN }}
          app_name: testingappmerpati.streamlit.app
